### ISSUE TITLE
Instantly closes audio programs when adding

### ISSUE THREAD

**Issue by audio2000** [brummer10/Ratatouille.lv2#20]
Linux Debian based distro
GTK based Desktop Environment
Ardour 8.6
Carla 2.5.5

I recently came across this plugin, have never used it before but it looks nice.
I tried opening this up in Carla as well as in Ardour and in both applications I noticed that the second I try inserting this plugin they instantly close.  

I was wondering if anyone else has experienced this before?

I tried both of the following plugin versions, I am not sure what the V3
Ratatouille.lv2-v0.8-linux-x86_64
Ratatouille.lv2-v3-v0.8-linux-x86_64

Thank You

**Comment by DevFreeTwo** [comment]
I can confirm this issue. 

Using Opensuse Leap 15.6 with an old Intel Core i5 CPU 750 here.
Carla as well as Ardour crash when loading either version (binary; x86_64 OR  V3).

In my console it says: "Ungültiger Maschinenbefehl (Speicherabzug geschrieben)" 
[= Invalid machine command (memory dump written) ]

This happens with all releases since 0.4, release 0.3 is the last that runs fine.

Probably the cpu optimizations introduced are the culprit.

**Comment by brummer10** [comment]
Yes, that is a issue with the optimisation flags. Could you please post the output from
`cat /proc/cpuinfo`

**Comment by DevFreeTwo** [comment]
Here the output of the first core, others have same feature set anyway.

`processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 30
model name      : Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
stepping        : 5
microcode       : 0xa
cpu MHz         : 2769.708
cache size      : 8192 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm ssbd ibrs ibpb stibp tpr_shadow flexpriority ept vpid dtherm ida vnmi flush_l1d
vmx flags       : vnmi preemption_timer invvpid ept_x_only flexpriority tsc_offset vtpr mtf vapic ept vpid
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips        : 5346.87
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
`

Danke dir vielmals Hermann

**Comment by brummer10** [comment]
So your CPU should be good for x86-64-v2 level optimisation (not v3). 
I've implemented some better checks for optimisation levels in the makefile, could you try to build from the latest git

```
git clone https://github.com/brummer10//Ratatouille.lv2.git
cd Ratatouille.lv2
git submodule update --init --recursive
make
make install
```

if that still don't work (let me know please), you could switch off all optimisations by using

`make SSE_CFLAGS="" FFT_FLAG=""`

**Comment by DevFreeTwo** [comment]
Hallo Hermann

after struggling with fixing dependencies and OpenSuSE's old g++ version I come to this error:

Ratatouille.cpp:23:10: fatal error: lv2/core/lv2.h: Datei oder Verzeichnis nicht gefunden


Can't you provide me with a binary? I'm in a time-crunch lately

**Comment by brummer10** [comment]
Yep, I've just pushed a new version (v0.9.1) out, here is the one without any optimisation flags applied 
https://github.com/brummer10/Ratatouille.lv2/releases/download/v0.9.1/Ratatouille.lv2-v0.9.1-linux-arm64.tar.xz


> Ratatouille.cpp:23:10: fatal error: lv2/core/lv2.h: Datei oder Verzeichnis nicht gefunden

you need the lv2-devel package.

**Comment by DevFreeTwo** [comment]
Yes, right, LV2. I thought it was automatically loaded as subpackage.

OK, the binary works here, though with some side-effects. It doesn't crash anymore.

When I first started it in Carla or Ardour, it wouldn't load neither NAM-files nor IRs.
Then after restarting both applications, it suddenly worked ??

In the file selection dialog i can't find directories set up as symbolic link. I use this as a shortcut, so i don't have to go through the directories (direct entry of the path to my NAM-folders not possible).
The symbolic links don't show up anymore.

**Comment by brummer10** [comment]
Yes, symlinks didn't work in the browser. 
The browser supports the XDG user dir specifications, that mean you could add a "Place" in your
~/.config/user-dirs.dirs file (If you don't have this file, simply create it) by just add a new line like this:
`XDG_NAM_DIR="/path/to/NAM/"`

That will add a place "NAM" to the left side Places in the browser.
You could do the same for aida-x files, IR files, . . .

**Comment by DevFreeTwo** [comment]
Alright. I got the compile to run through now.

The symlinks used to work in version 0.3.

Thanks for the user-dirs tip, this is a good work-around for me.
The only thing I find annoying is, that in the files dialog all paths are displayed as full path. But that should probably go into another issue, right?

So for me the original issue here is fixed and can be closed.

Should I open a new issue for the symlinks?

**Comment by brummer10** [comment]
yes, please open a new issue for that so I can't forget it. 
It may take some time before I could look into it.

**Comment by DevFreeTwo** [comment]
OK, habe ein neues Issue dafür eröffnet.

Hermann, vielen Dank für die schnelle Hilfe und den Fix. Und deine hervorragenden Leistungen rund um Open-Source Amp-Simulation. Danke !

Hier zwei Tipps, die evtl. interessant fü dich sein könnten:
- [Physik der Elektrogitarre, inkl. fundierter Info zu Röhrensound vs. Transistor](https://www.youtube.com/@physik-der-elektrogitarre/videos)
- [Tweed Deluxe Emulation JSFX, inkl. detailliertes Paper zur Umsetzung/Verfahren](https://www.helmutkelleraudio.de/)

**Comment by brummer10** [comment]
@DevFreeTwo Danke. 
Dein Hinweis das symlinks in version 0.3 noch funktioniert haben half mir den Fehler schnell zu beheben. 
Danke für die Links, die tweed Deluxe simulation ist sehr interessant, ist das von dir?

**Comment by DevFreeTwo** [comment]
@brummer10 Gerne geschehen.

Der Tweed Deluxe ist nicht von mir. Bin eher durch Zufall über das GITEC Forum darauf gestoßen. Das ist ein Verein, der sich der Förderung der  wissenschaftlichen Erforschung der E-Gitarren Technik widmet. Also kurz, die Fakten beleuchten, statt dem Marketing.

Auf deren Website gibt es allerhand interessantes zu erfahren. Auch zu Modellierung  oder DSP Programmierung. Der ebenfalls verlinkte Youtube-Kanal hat auch etwas mit dem Verein zu tun.

Helmut Keller freut sich bestimmt über Feedback..
